apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-db
  template:
    metadata:
      labels:
        app: student-db
    spec:
      containers:
      - name: mariadb
        image: {{ .Values.db.image }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: student-db-secret
              key: mysql-password
        ports:
        - containerPort: {{ .Values.db.port }}
        volumeMounts:
        - name: db-init
          mountPath: /docker-entrypoint-initdb.d
        - name: db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: db-init
        configMap:
          name: student-db-init
      - name: db-data
        persistentVolumeClaim:
          claimName: student-db-pvc
