apiVersion: v1
kind: ConfigMap
metadata:
  name: student-db-init
data:
  schema.sql: |
    CREATE TABLE IF NOT EXISTS students (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(150),
      contact_number VARCHAR(30),
      address VARCHAR(255),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
