apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-web
spec:
  replicas: {{ .Values.web.replicas }}
  selector:
    matchLabels:
      app: student-web
  template:
    metadata:
      labels:
        app: student-web
    spec:
      containers:
      - name: student-web
        image: {{ .Values.web.image }}
        ports:
        - containerPort: {{ .Values.web.containerPort }}
        volumeMounts:
        - name: web-content
          mountPath: /usr/local/apache2/htdocs
      volumes:
      - name: web-content
        configMap:
          name: student-web-config
          items:
            - key: index.html
              path: index.html
